name: InteraMusicPlayer

options:
  deploymentTarget:
    iOS: 16.0
  bundleIdPrefix: com.interaauditsolutions
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: 5.0
    DEVELOPMENT_TEAM: ""

targets:
  InteraMusicPlayer:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources:
      - path: InteraMusicPlayer
        excludes:
          - Info.plist
    info:
      path: InteraMusicPlayer/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.interaauditsolutions.music
        PRODUCT_NAME: InteraMusic
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: NO
