name: InteraMusicPlayer

options:
  deploymentTarget:
    iOS: 16.0
  bundleIdPrefix: com.interaauditsolutions

settings:
  base:
    SWIFT_VERSION: 5.0

targets:
  InteraMusicPlayer:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    sources:
      - AudioPlayerModel.swift
      - ContentView.swift
      - InteraMusicPlayerApp.swift
    info:
      path: Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.interaauditsolutions.music
        PRODUCT_NAME: InteraMusic
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: NO
